name: android
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.63.0
  http: ^0.13.5
  cupertino_icons: ^1.0.8
  flutter_card_swiper: ^7.0.2
  font_awesome_flutter: ^10.8.0
  line_icons: ^2.0.3
  eva_icons_flutter: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/employee1.png
    - assets/employee2.png
    - assets/employee3.png
    - assets/employee4.png
    - assets/employee5.png
    - assets/icons/


  fonts:
    - family: PermanentMarker
      fonts:
        - asset: assets/fonts/PermanentMarker-Regular.ttf
    - family: Bangers
      fonts:
        - asset: assets/fonts/Bangers-Regular.ttf
    - family: TitanOne
      fonts:
        - asset: assets/fonts/TitanOne-Regular.ttf
